// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1281: x0 => ({audio: x0}),
      _1282: (x0,x1) => x0.getUserMedia(x1),
      _1283: x0 => x0.getAudioTracks(),
      _1284: x0 => x0.stop(),
      _1285: (x0,x1) => x0.removeTrack(x1),
      _1286: x0 => x0.close(),
      _1287: (x0,x1) => x0.warn(x1),
      _1288: x0 => x0.getSettings(),
      _1289: x0 => ({sampleRate: x0}),
      _1290: x0 => new AudioContext(x0),
      _1291: () => new AudioContext(),
      _1294: (x0,x1) => x0.connect(x1),
      _1295: x0 => globalThis.URL.createObjectURL(x0),
      _1296: (x0,x1) => x0.createMediaStreamSource(x1),
      _1297: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1297(f,arguments.length,x0) }),
      _1298: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1298(f,arguments.length,x0) }),
      _1299: (x0,x1) => x0.addModule(x1),
      _1300: x0 => ({parameterData: x0}),
      _1301: (x0,x1,x2) => new AudioWorkletNode(x0,x1,x2),
      _1302: x0 => ({name: x0}),
      _1303: (x0,x1) => x0.query(x1),
      _1305: x0 => globalThis.URL.revokeObjectURL(x0),
      _1310: x0 => x0.disconnect(),
      _1311: x0 => x0.stop(),
      _1312: (x0,x1,x2) => ({mimeType: x0,audioBitsPerSecond: x1,bitsPerSecond: x2}),
      _1313: (x0,x1) => new MediaRecorder(x0,x1),
      _1314: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1314(f,arguments.length,x0) }),
      _1315: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1315(f,arguments.length,x0) }),
      _1316: (x0,x1) => x0.start(x1),
      _1317: x0 => ({type: x0}),
      _1318: (x0,x1) => new Blob(x0,x1),
      _1319: (x0,x1) => globalThis.jsFixWebmDuration(x0,x1),
      _1320: x0 => x0.createAnalyser(),
      _1321: (x0,x1) => x0.getFloatFrequencyData(x1),
      _1322: x0 => globalThis.MediaRecorder.isTypeSupported(x0),
      _1335: () => new webkitSpeechRecognition(),
      _1336: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1336(f,arguments.length,x0) }),
      _1337: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1337(f,arguments.length,x0) }),
      _1338: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1338(f,arguments.length,x0) }),
      _1339: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1339(f,arguments.length,x0) }),
      _1340: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1340(f,arguments.length,x0) }),
      _1341: x0 => x0.stop(),
      _1342: x0 => x0.abort(),
      _1343: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1343(f,arguments.length,x0) }),
      _1344: x0 => x0.start(),
      _1345: (x0,x1) => x0.item(x1),
      _1346: (x0,x1) => x0.item(x1),
      _1354: (x0,x1) => x0.getItem(x1),
      _1355: (x0,x1) => x0.removeItem(x1),
      _1356: (x0,x1,x2) => x0.setItem(x1,x2),
      _1357: () => new SpeechSynthesisUtterance(),
      _1358: x0 => x0.pause(),
      _1359: x0 => x0.resume(),
      _1360: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1360(f,arguments.length,x0) }),
      _1361: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1361(f,arguments.length,x0) }),
      _1362: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1362(f,arguments.length,x0) }),
      _1363: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1363(f,arguments.length,x0) }),
      _1364: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1364(f,arguments.length,x0) }),
      _1365: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1365(f,arguments.length,x0) }),
      _1366: (x0,x1) => x0.speak(x1),
      _1367: x0 => x0.cancel(),
      _1368: x0 => x0.getVoices(),
      _1369: Date.now,
      _1371: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1372: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1373: () => new Error().stack,
      _1374: () => typeof dartUseDateNowForTicks !== "undefined",
      _1375: () => 1000 * performance.now(),
      _1376: () => Date.now(),
      _1377: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1378: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1379: () => new WeakMap(),
      _1380: (map, o) => map.get(o),
      _1381: (map, o, v) => map.set(o, v),
      _1382: (exn) => exn.toString(),
      _1383: (exn) => exn.stack,
      _1384: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1385: x0 => new WeakRef(x0),
      _1386: x0 => x0.deref(),
      _1393: () => globalThis.WeakRef,
      _1397: s => JSON.stringify(s),
      _1398: s => printToConsole(s),
      _1399: (o, p, r) => o.replaceAll(p, () => r),
      _1400: (o, p, r) => o.replace(p, () => r),
      _1401: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1402: s => s.toUpperCase(),
      _1403: s => s.trim(),
      _1404: s => s.trimLeft(),
      _1405: s => s.trimRight(),
      _1406: (string, times) => string.repeat(times),
      _1407: Function.prototype.call.bind(String.prototype.indexOf),
      _1408: (s, p, i) => s.lastIndexOf(p, i),
      _1409: (string, token) => string.split(token),
      _1410: Object.is,
      _1414: (o, c) => o instanceof c,
      _1415: o => Object.keys(o),
      _1417: (o,s,v) => o[s] = v,
      _1445: x0 => new Array(x0),
      _1447: x0 => x0.length,
      _1449: (x0,x1) => x0[x1],
      _1450: (x0,x1,x2) => { x0[x1] = x2 },
      _1453: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1455: x0 => new Int8Array(x0),
      _1456: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1458: x0 => new Uint8ClampedArray(x0),
      _1460: x0 => new Int16Array(x0),
      _1462: x0 => new Uint16Array(x0),
      _1464: x0 => new Int32Array(x0),
      _1466: x0 => new Uint32Array(x0),
      _1468: x0 => new Float32Array(x0),
      _1470: x0 => new Float64Array(x0),
      _1493: () => Symbol("jsBoxedDartObjectProperty"),
      _1494: x0 => x0.random(),
      _1495: (x0,x1) => x0.getRandomValues(x1),
      _1496: () => globalThis.crypto,
      _1497: () => globalThis.Math,
      _1510: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1511: (handle) => clearTimeout(handle),
      _1512: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1513: (handle) => clearInterval(handle),
      _1514: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1515: () => Date.now(),
      _1516: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1517: (x0,x1) => x0.exec(x1),
      _1518: (x0,x1) => x0.test(x1),
      _1519: x0 => x0.pop(),
      _1521: o => o === undefined,
      _1523: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1525: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1526: o => o instanceof RegExp,
      _1527: (l, r) => l === r,
      _1528: o => o,
      _1529: o => o,
      _1530: o => o,
      _1531: b => !!b,
      _1532: o => o.length,
      _1534: (o, i) => o[i],
      _1535: f => f.dartFunction,
      _1536: () => ({}),
      _1537: () => [],
      _1539: () => globalThis,
      _1540: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1542: (o, p) => o[p],
      _1543: (o, p, v) => o[p] = v,
      _1544: (o, m, a) => o[m].apply(o, a),
      _1546: o => String(o),
      _1547: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1548: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1548(f,arguments.length,x0) }),
      _1549: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1549(f,arguments.length,x0,x1) }),
      _1550: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1551: o => [o],
      _1552: (o0, o1) => [o0, o1],
      _1553: (o0, o1, o2) => [o0, o1, o2],
      _1554: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1555: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1556: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1559: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1560: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1561: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1562: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1563: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1564: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1565: x0 => new ArrayBuffer(x0),
      _1566: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1568: x0 => x0.index,
      _1570: x0 => x0.flags,
      _1571: x0 => x0.multiline,
      _1572: x0 => x0.ignoreCase,
      _1573: x0 => x0.unicode,
      _1574: x0 => x0.dotAll,
      _1575: (x0,x1) => { x0.lastIndex = x1 },
      _1576: (o, p) => p in o,
      _1577: (o, p) => o[p],
      _1580: () => new XMLHttpRequest(),
      _1583: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1584: (x0,x1) => x0.send(x1),
      _1585: x0 => x0.send(),
      _1586: (x0,x1) => x0.createElement(x1),
      _1589: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1589(f,arguments.length,x0) }),
      _1590: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1590(f,arguments.length,x0) }),
      _1591: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1592: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1598: (x0,x1,x2) => x0.open(x1,x2),
      _1599: x0 => x0.abort(),
      _1600: x0 => x0.getAllResponseHeaders(),
      _1601: () => new AbortController(),
      _1602: x0 => x0.abort(),
      _1603: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1604: (x0,x1) => globalThis.fetch(x0,x1),
      _1605: (x0,x1) => x0.get(x1),
      _1606: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1606(f,arguments.length,x0,x1,x2) }),
      _1607: (x0,x1) => x0.forEach(x1),
      _1608: x0 => x0.getReader(),
      _1609: x0 => x0.cancel(),
      _1610: x0 => x0.read(),
      _1611: (x0,x1) => x0.appendChild(x1),
      _1612: (x0,x1) => x0.append(x1),
      _1613: (x0,x1) => x0.item(x1),
      _1614: (x0,x1) => x0.key(x1),
      _1615: o => o instanceof Array,
      _1620: a => a.pop(),
      _1621: (a, i) => a.splice(i, 1),
      _1622: (a, s) => a.join(s),
      _1623: (a, s, e) => a.slice(s, e),
      _1625: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1626: a => a.length,
      _1628: (a, i) => a[i],
      _1629: (a, i, v) => a[i] = v,
      _1631: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1632: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1634: o => o instanceof Uint8Array,
      _1635: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1636: o => o instanceof Int8Array,
      _1637: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1638: o => o instanceof Uint8ClampedArray,
      _1639: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1640: o => o instanceof Uint16Array,
      _1641: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1642: o => o instanceof Int16Array,
      _1643: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1644: o => o instanceof Uint32Array,
      _1645: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1646: o => o instanceof Int32Array,
      _1647: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1649: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1650: o => o instanceof Float32Array,
      _1651: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1652: o => o instanceof Float64Array,
      _1653: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1654: (t, s) => t.set(s),
      _1655: l => new DataView(new ArrayBuffer(l)),
      _1656: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1658: o => o.buffer,
      _1659: o => o.byteOffset,
      _1660: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1661: (b, o) => new DataView(b, o),
      _1662: (b, o, l) => new DataView(b, o, l),
      _1663: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1664: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1665: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1666: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1667: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1668: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1669: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1670: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1671: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1672: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1673: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1674: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1677: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1678: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1679: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1680: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1681: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1682: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1683: Function.prototype.call.bind(Number.prototype.toString),
      _1684: Function.prototype.call.bind(BigInt.prototype.toString),
      _1685: Function.prototype.call.bind(Number.prototype.toString),
      _1686: (d, digits) => d.toFixed(digits),
      _1784: x0 => x0.readyState,
      _1786: (x0,x1) => { x0.timeout = x1 },
      _1788: (x0,x1) => { x0.withCredentials = x1 },
      _1789: x0 => x0.upload,
      _1790: x0 => x0.responseURL,
      _1791: x0 => x0.status,
      _1792: x0 => x0.statusText,
      _1794: (x0,x1) => { x0.responseType = x1 },
      _1795: x0 => x0.response,
      _1807: x0 => x0.loaded,
      _1808: x0 => x0.total,
      _3109: (x0,x1) => { x0.src = x1 },
      _3111: (x0,x1) => { x0.type = x1 },
      _3129: (x0,x1) => { x0.charset = x1 },
      _3578: () => globalThis.window,
      _3641: x0 => x0.navigator,
      _3905: x0 => x0.localStorage,
      _4014: x0 => x0.mediaDevices,
      _4016: x0 => x0.permissions,
      _4081: x0 => x0.data,
      _4118: (x0,x1) => { x0.onmessage = x1 },
      _4238: x0 => x0.length,
      _5626: x0 => x0.destination,
      _5630: x0 => x0.state,
      _5631: x0 => x0.audioWorklet,
      _5734: (x0,x1) => { x0.fftSize = x1 },
      _5735: x0 => x0.frequencyBinCount,
      _5737: (x0,x1) => { x0.minDecibels = x1 },
      _5739: (x0,x1) => { x0.maxDecibels = x1 },
      _5741: (x0,x1) => { x0.smoothingTimeConstant = x1 },
      _5995: x0 => x0.port,
      _6175: x0 => x0.signal,
      _6187: x0 => x0.length,
      _6248: () => globalThis.document,
      _6331: x0 => x0.head,
      _6666: x0 => x0.id,
      _6667: (x0,x1) => { x0.id = x1 },
      _6694: x0 => x0.children,
      _8013: x0 => x0.value,
      _8015: x0 => x0.done,
      _8196: x0 => x0.size,
      _8588: x0 => x0.mimeType,
      _8589: x0 => x0.state,
      _8593: (x0,x1) => { x0.onstop = x1 },
      _8595: (x0,x1) => { x0.ondataavailable = x1 },
      _8620: x0 => x0.data,
      _8710: x0 => x0.url,
      _8712: x0 => x0.status,
      _8714: x0 => x0.statusText,
      _8715: x0 => x0.headers,
      _8716: x0 => x0.body,
      _8845: (x0,x1) => { x0.lang = x1 },
      _8847: (x0,x1) => { x0.continuous = x1 },
      _8849: (x0,x1) => { x0.interimResults = x1 },
      _8857: (x0,x1) => { x0.onspeechstart = x1 },
      _8865: (x0,x1) => { x0.onresult = x1 },
      _8867: (x0,x1) => { x0.onnomatch = x1 },
      _8869: (x0,x1) => { x0.onerror = x1 },
      _8871: (x0,x1) => { x0.onstart = x1 },
      _8873: (x0,x1) => { x0.onend = x1 },
      _8874: x0 => x0.error,
      _8876: x0 => x0.transcript,
      _8877: x0 => x0.confidence,
      _8878: x0 => x0.length,
      _8880: x0 => x0.length,
      _8882: x0 => x0.results,
      _9098: x0 => x0.state,
      _9758: x0 => x0.sampleRate,
      _9770: x0 => x0.channelCount,
      _12332: x0 => x0.name,
      _13050: () => globalThis.console,
      _13074: () => globalThis.speechSynthesis,
      _13075: (x0,x1) => { x0.lang = x1 },
      _13077: (x0,x1) => { x0.pitch = x1 },
      _13080: (x0,x1) => { x0.rate = x1 },
      _13082: (x0,x1) => { x0.text = x1 },
      _13083: (x0,x1) => { x0.voice = x1 },
      _13084: x0 => x0.voice,
      _13086: (x0,x1) => { x0.volume = x1 },
      _13087: (x0,x1) => { x0.onstart = x1 },
      _13088: (x0,x1) => { x0.onend = x1 },
      _13089: (x0,x1) => { x0.onpause = x1 },
      _13090: (x0,x1) => { x0.onresume = x1 },
      _13091: (x0,x1) => { x0.onerror = x1 },
      _13092: (x0,x1) => { x0.onboundary = x1 },
      _13094: x0 => x0.lang,
      _13095: x0 => x0.localService,
      _13096: x0 => x0.name,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
